# Generated by Django 5.1.5 on 2025-01-28 20:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_enrollment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
